---
title: "Research"
author: "Mohamed Salem"
header-includes:
  - \usepackage{mathrsfs}
  - \usepackage{cancel}
  - \usepackage{amsmath}
  - \usepackage{booktabs}
  - \usepackage{multirow}
  - \usepackage{setspace}
  - \usepackage{subcaption}
  - \usepackage{caption}
  - \usepackage{tikz}
  - \usepackage{float}
  - \usepackage{setspace}
  - \usepackage{bm}
output:
  pdf_document: default
  html_document:
    df_print: paged
geometry: margin=1in
fontsize: 10pt
mainfont: Helvetica
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=60),tidy=TRUE,fig.height = 4.4, fig.width = 6, fig.align = 'center', fig.pos = "H", fig.keep = "all", warning = FALSE, message = FALSE)
```

```{r , echo=F,results='hide', collapse=TRUE, include=FALSE}
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(Matrix))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(car))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(stargazer))
suppressPackageStartupMessages(library(quantreg))
suppressPackageStartupMessages(library(rpart))
suppressPackageStartupMessages(library(fMultivar))
suppressPackageStartupMessages(library(LaplacesDemon))
suppressPackageStartupMessages(library(mvtnorm))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(invgamma))
suppressPackageStartupMessages(library(network))
suppressPackageStartupMessages(library(sna))
suppressPackageStartupMessages(library(geomnet))
suppressPackageStartupMessages(library(grplasso))
suppressPackageStartupMessages(library(grpreg))
suppressPackageStartupMessages(library(ggnetwork))
#suppressPackageStartupMessages(library(combinat))
```


```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 
# 2 pathways
N = 1000   # Number of iterations for SSVS
set.seed(1234)  # seed

# Randomly generated 10 features from first path via standard normal
first_path_features = data.frame(matrix(rnorm(1000,0,1), nrow = 100))

# Applied Gaussian kernel to first path 
kmat_1 = exp(-1/2*as.matrix(dist(first_path_features, diag = TRUE, upper=TRUE)))

# Dataframe generation for remaining paths
second_path_features = data.frame(matrix(rnorm(1000,0,1), nrow = 100))

# Creating a y 
y =  10*cos(first_path_features$X1)+3*(first_path_features$X2^2)+5*sin(first_path_features$X3)+6*exp(second_path_features$X4/3)*second_path_features$X4+8*cos(second_path_features$X5)+first_path_features$X2*first_path_features$X1*second_path_features$X5+rnorm(100)


y = (y-mean(y))/sd(y)

# Generating other paths

distance_matrix_1 = as.matrix(dist(second_path_features, diag = TRUE, upper=TRUE)) 

#distance matrix should be 100x100
kmat_2 = exp(-1/2*as.matrix(dist(second_path_features, diag = TRUE, upper=TRUE)))
#kmat_2 = matrix(rt(10000,df=2), nrow = 100) #change to polynomial kernel
kmat_2 = exp(-1/2*as.matrix(dist(kmat_2, diag = TRUE, upper=TRUE))) # try making 2 smaller
# Creating full feature matrix
kmat = as.matrix(cbind(kmat_1, kmat_2))

# Creating a y without the random noise for checking results
y_epsilon =  10*cos(first_path_features$X1)+3*(first_path_features$X2^2)+5*sin(first_path_features$X3)+6*exp(second_path_features$X4/3)*second_path_features$X4+8*cos(second_path_features$X5)+first_path_features$X2*first_path_features$X1*second_path_features$X5

# True lambda
lambda = 1/var(y_epsilon)

# Theoretical coefficient solutions (can assume independennce then iterate while conditioning as Y- \gamma*K_i*alpha insted of Y)
alpha_1_opt = ginv(lambda*diag(100)+(kmat_1))%*%y
alpha_2_opt = ginv(lambda*diag(100)+(kmat_2))%*%y

# Correlation between theoretical solution and true y
cor((kmat_1)%*%alpha_1_opt,y_epsilon)
```

We implement the Bayesian Ising Graphical model for selecting the genes below. Which genes are selected is essentially a function of the correlation of the individual genes with the response as well as their correlation with fellow friendly genes within the same pathway:

```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 

BIGM = function(path_features, y, curr_xi, N=1000, phi=1){
    y_s = scale(y)
    X_s = scale(path_features)
    MMR = matrix(0, nrow = dim(X_s)[1], ncol = dim(X_s)[2])
    for(i in 1:(dim(X_s)[2])){
      MMR[,i] = (lm(y~X_s[,i]))$coefficients[2]*X_s[,i]
    }
    
    J = -phi/2*t(MMR)%*%(MMR)
    h = phi*t(MMR)%*%(y-0.5*MMR%*%c(rep(1,dim(X_s)[2])))
    
    #curr_xi = sample(c(0,1), 10, replace = T)
    
    #Matrix to hold metropolis results
    cmat = matrix(NA, nrow = N+1, ncol = length(curr_xi))
    cmat[1,] = curr_xi
    
    # Metropolis algorithm
    for (i in 1:N){
      for (j in 1:length(curr_xi)){
        
        ref_curr_xi = replace(curr_xi, curr_xi==0, -1)
        xi_int_mat_curr = c(ref_curr_xi)%*%t(c(ref_curr_xi))
        xi_int_mat_curr = replace(xi_int_mat_curr, xi_int_mat_curr==-1, 0)
        rm(ref_curr_xi)
        
        U_current = -sum(J*upper.tri(xi_int_mat_curr, diag = FALSE))-sum(h*curr_xi)
        
        prop_xi = curr_xi
        prop_xi[j] = abs(curr_xi[j]-1)
        
        ref_prop_xi = replace(prop_xi, prop_xi==0, -1)
        xi_int_mat_prop = c(ref_prop_xi)%*%t(c(ref_prop_xi))
        xi_int_mat_prop = replace(xi_int_mat_prop, xi_int_mat_prop==-1, 0)
        rm(ref_prop_xi)
        
        U_proposed = -sum(J*upper.tri(xi_int_mat_prop, diag = FALSE))-sum(h*prop_xi)
        
        delta_U = U_proposed - U_current
        
        prob_flip = min(c(1, exp(-1*delta_U)))
        
        flipper = rbinom(1,1,prob_flip)  
        
        if (flipper == 1){
          curr_xi = prop_xi  
        }
        
      }
      
      cmat[i+1,] = curr_xi
      
    }
    
    #curr_xi = apply(cmat[(N+1-50+1):(N+1),], 2, modefunc)
    curr_xi = as.double(colSums(cmat[(N+1-50+1):(N+1),])/((N+1)-(N+1-50+1)+1)>0.5)
    
    return(curr_xi)
}
```


```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 

GaussianKernelize = function(path_features, curr_xi){
  
  holdr = as.matrix(path_features)%*%diag(curr_xi)
  holdr = holdr[, colSums(abs(holdr)) != 0]
  kmat = exp(-1/2*as.matrix(dist(holdr, diag = TRUE, upper=TRUE)))
    
  return(kmat)
}
```

```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 

modefunc <- function(x){
    tabresult <- tabulate(x)
    themode <- which(tabresult == max(tabresult))
    if(sum(tabresult == max(tabresult))>1) themode <- NA
    return(themode)
}
```

```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 
# loading the data
dat <- read_xlsx("C:/My Files/Vtech/PhD Research/data.xlsx")
# keeping only relevant and chosen non-relevant pathway genes
listr = list('Pathway',NA,133,39,49,36,71,1,2,3,4,5)
deletr = numeric()
j=0

for (i in 1:(dim(dat)[2])){
  if (!(dat[36,i] %in% listr)){
    j = j+1
    deletr[j] = i
  }
}

dat = dat[-deletr]

# dropping demographic variables
dat[ ,c('ID', 'WHR', 'Age','Cholesterol','M value','Triglycerides', 'Body Mass Index', 'Insulin 0', 'Insulin 120','Glycogen (mmol/kg)','VO2 max (ml/kg/min total body weight)','Glucose 0 capillary blood who 85','status')] <- list(NULL)
```

```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 
# 10 pathways of data
N = 1000   # Number of iterations for SSVS
set.seed(1234)  # seed
num_pw = 2
distn = "mvn"

og_df = dat[-c(36),]
group_identifier_vector = c(dat[36,])
group_list = c("1","133")

pathway_creator = function(og_df, group_identifier_vector, group_list, num_pw){
  listr = list()
  for(i in 1:num_pw){
    listr[[i]] = as.data.frame(scale(og_df[,c(group_identifier_vector==group_list[i])]))
  }
  
  pwy_dfs = listr
  
  return(pwy_dfs)
}

pwy_dfs = pathway_creator(og_df, group_identifier_vector, group_list, num_pw)

kmat_creator = function(df_list, num_pw){
  listr = list()
  for(i in 1:num_pw){
    listr[[i]] = exp(-1/2*as.matrix(dist(pwy_dfs[[i]], diag = TRUE, upper=TRUE)))
  }
  
  kmat_dfs = listr
  
  return(kmat_dfs)
}

kmat_dfs = kmat_creator(pwy_dfs, num_pw)

# Creating a y 
y = dat$`Glucose 120 capillary blood who 85`
y = y[-c(36)]
y =  as.numeric(y)

# Standardizing y
y = scale(y)
y = as.numeric(y)


# Setting up overall variance placeholder
sigmasq = data.frame(rep(NA, N))
sigmasq[1,] = 1

# Setting up placeholder for coefficient variance
sigmasq_alpha = data.frame(rep(NA, N))
sigmasq_alpha[1,] = 1

# Inverse Gamma parameters for overall variance prior
a = 0.5
b = 0.5

# Inverse Gamma parameters for coefficient variance prior
a_al = 0.5
b_al = 0.5

# total number of variables
var_tot = 0
for(i in 1:num_pw){
  var_tot = var_tot+dim(pwy_dfs[[i]])[2]
}

# Setting up placeholder for coefficients
alpha_creator = function(num_pw, N, pwy_dfs, init = 0.5){
  listr = list()
  for(i in 1:num_pw){
    listr[[i]] = matrix(NA, nrow = N, ncol = dim(pwy_dfs[[i]])[1])
    listr[[i]][1,] = init
  }
  
  alpha_mats = listr
  
  return(alpha_mats)
}

alpha_mats = alpha_creator(num_pw, N, pwy_dfs)

# Setting Binomial probability
pi_0 = 0.5

# momentum coefficient
mom = 0.0

# Setting up a placeholder for path selection variable (10 pathways)
gamma = matrix(NA, nrow = N, ncol = num_pw)
# Initializing path selection variable
gamma[1,] = rep(1,num_pw)
gamma[1,] = c(1,0)


prob_notnull_creator = function(num_pw, N, pwy_dfs, init = 0){
  listr = list()
  for(i in 1:num_pw){
    listr[[i]] = rep(init,N)
  }
  
  prob_not_null_vecs = listr
  
  return(prob_not_null_vecs)
}

prob_not_null_vecs = prob_notnull_creator(num_pw, N, pwy_dfs)

lister = list()
for(i in 1:100000){
  lister[i] = list(sample(c(-1,1), size = num_pw, replace=TRUE))
}
length(unique(lister))
lister = unique(lister)

sums_mat = rep(NA,(2^(length(gamma[1,]))))

for(i in 1:(2^(length(gamma[1,])))){
  sums_mat[i] = exp(sum(c(lister[[i]])%*%t(c(lister[[i]]))*upper.tri(c(lister[[i]])%*%t(c(lister[[i]])), diag = FALSE)))
}


ising_denom = 0

W_mat = matrix(1, nrow = (length(gamma[1,])), ncol = (length(gamma[1,])))

for(i in 1:(2^(length(gamma[1,])))){
      mat_ph = c(lister[[i]])%*%t(c(lister[[i]]))
      mat_ph = replace(mat_ph, mat_ph == -1, 0)
      mat_ph = W_mat*mat_ph
      ising_denom = ising_denom + exp(sum(mat_ph*upper.tri(mat_ph, diag = FALSE)))
      #mat_glob_i = mat_ph
  }

curr_xi_creator = function(num_pw, N, pwy_dfs){
  listr = list()
  for(i in 1:num_pw){
    listr[[i]] = as.matrix(rbind(sample(c(0,1), dim(pwy_dfs[[i]])[2], replace = T),matrix(NA, nrow=N-1, ncol=dim(pwy_dfs[[i]])[2])))
  }
  
  curr_xi_dfs = listr
  
  return(curr_xi_dfs)
}

curr_xi_dfs = curr_xi_creator(num_pw, N, pwy_dfs)

i=2

for (i in 2:N){
  alpha_mats_k = lapply(alpha_mats, function(x) {x <- x[i-1, ]})
  if(distn == "mvn"){
    for (j in 1:num_pw){
      # sampling first path coefficients from spike slab prior
      alpha_mats[[j]][i,] = (gamma[i-1,j])*rmvnorm(1, ginv(sigmasq[i-1,]/sigmasq_alpha[i-1,]*kmat_dfs[[j]]+t(kmat_dfs[[j]])%*%kmat_dfs[[j]])%*%t(kmat_dfs[[j]])%*%(y-0.5*Reduce("+",(Map('%*%',kmat_dfs,alpha_mats_k)))+0.5*kmat_dfs[[j]]%*%alpha_mats[[j]][i-1,]),sigmasq[i-1,]*ginv(sigmasq[i-1,]/sigmasq_alpha[i-1,]*kmat_dfs[[j]]+t(kmat_dfs[[j]])%*%kmat_dfs[[j]]))+(1-gamma[i-1,j])*rmvnorm(1, rep(0,length(y)),0.001*diag(length(y)))
    }
      
      # sampling new phi
      sigmasq[i,] = (length(y)/2*1/(0.5*sum((y-(gamma[i-1,1])*kmat_1%*%alpha_1[i,]+(gamma[i-1,2])*kmat_2%*%alpha_2[i,])^2)))#1/rgamma(1,length(y)/2,0.5*sum((y-kmat_1%*%alpha_1[i,]+kmat_2%*%alpha_2[i,])^2))
  
  } else if(distn == "ald"){
    
  }
  
    sigmasq_alpha[i,] = 1.0
    
    reform_gamma_mat = replace(gamma[i-1,], gamma[i-1,]==0, -1)
    delta_mat = (reform_gamma_mat)%*%t(reform_gamma_mat)
    delta_mat = replace(delta_mat, delta_mat==-1, 0)
    upper_tri_delta_mat = delta_mat*upper.tri(delta_mat, diag = FALSE)
    
    # Ising prior
    prior_ising_H0 = exp(sum(upper_tri_delta_mat))/ising_denom
    
    # computing numerator as: pdf of all coefficients \times pdf of current variance 
    # \times pdf of gamma vector (last one cancels out)
    
    alpha_mats_k = lapply(alpha_mats, function(x) {x <- x[i, ]})
    
    if(distn == "mvn"){
      for (j in 1:num_pw){
        
        d = dmvnorm(y, (Reduce("+",(Map('%*%',kmat_dfs,alpha_mats_k)))),1*diag(length(y)))*prior_ising_H0
        
        e = dmvnorm(y, (Reduce("+",(Map('%*%',kmat_dfs,alpha_mats_k)))-kmat_dfs[[j]]%*%alpha_mats[[j]][i,]),1*
                      diag(length(y)))*(1-prior_ising_H0)
        
        # Computing the probability that gamma j equals 1
        prob_not_null_vecs[[j]][i] = d/(d+e)
    
        if(prob_not_null_vecs[[j]][i] == "NaN"){
          prob_not_null_vecs[[j]][i] = 0
        } else {}
        
        # Updating our value for gamma 1
        if(prob_not_null_vecs[[j]][i]>=0.5){
          gamma[i,j] = 1
        } else {gamma[i,j] = 0}
      }
    } else if(distn == "ald"){}
      
    # Gene Selection
    if((i==2)|(i%%500==0)){
      for(j in 1:num_pw){
        curr_xi_dfs[[j]][i,] = BIGM(pwy_dfs[[j]], y, curr_xi_dfs[[j]][i-1,], phi = (1/sigmasq[i,]))  
        # Rebuilding Pathways using only selected genes
        kmat_dfs[[j]] = GaussianKernelize(pwy_dfs[[j]], curr_xi_dfs[[j]][i,])
      }
      
    } else {
      for(j in 1:num_pw){
        curr_xi_dfs[[j]][i,] = curr_xi_dfs[[j]][i-1,]
      }
    }
}

av1 = alpha[(N-250):N,]
av2 = gamma[(N-250):N,]

sum(gamma[,1]==1)
sum(gamma[,2]==1)


for(j in 1:num_pw){
  print(paste("Gamma", j, "inclusion prob:", sum(av2[,j]==1)/251)) 
}

for(j in 1:num_pw){
  for(k in 1:dim(pwy_dfs[[j]])[2]){
    print(paste("Xi", k, "in pathway", j, "inclusion prob:", sum(curr_xi_dfs[[j]][(N-250):N,k])/251))   
  }
}

for(j in 1:num_pw){
  alpher = colSums(alpha_mats[[j]][(N-250):N,])/251
  print(paste("Correlation between pathway", j, "and the response variable is:", cor((kmat_dfs[[j]])%*%alpher,y))) 
}

alpha_mats_k = lapply(alpha_mats, function(x) {x <- x[(N-250):N, ]})
alpha_mats_k = lapply(alpha_mats_k, function(x) {x <- colMeans(x)})

print(paste("Correlation between full model and the response variable is:", cor(Reduce("+",(Map('%*%',kmat_dfs,alpha_mats_k))),y))) 

for(j in 1:num_pw){
  print(paste("Avg prob inclusion pathway", j,"is:", mean(prob_not_null_vecs[[j]][2:N]))) 
}

#quantile(prob1,c(0.025,0.975))
```

```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 
# Visualizations
total_genes = Reduce("+",lapply(pwy_dfs, function(x) {x <- dim(x)[2]}))
node_mat = data.frame(matrix(NA, nrow = total_genes, ncol = 3))
node_mat[1:total_genes,1] = do.call(c, lapply(pwy_dfs, function(x) {x <- colnames(x)}))
colnames(node_mat) = c("gene_name", "pathway_number", "status")
rownames(node_mat) <- as.character(node_mat$gene_name)
for(j in 1:num_pw){
  node_mat[c(colnames(pwy_dfs[[j]])),2] = j
  node_mat[c(colnames(pwy_dfs[[j]])),3] = as.numeric(colSums(curr_xi_dfs[[j]][(N-250):N,])/251>0.5)   
}

tail_xi = lapply(curr_xi_dfs, function(x) {x <- sum(as.numeric(colMeans(x[(N-250):N,])>0.5))})
edge_mat = data.frame(matrix(NA,nrow = Reduce("+",lapply(tail_xi, function(x) {x <- choose(x,2)})), ncol =2))
colnames(edge_mat) = c("Source", "Target")

vec = c(node_mat$gene_name)
inr = unique(vec[c(as.logical(node_mat$status))])[-1]
ph_mat = expand.grid(inr, inr)

g=c()
for(i in 1:dim(ph_mat)[1]){
  if(ph_mat[i,1]==ph_mat[i,2]){
    g = append(g,i)
  }
}

df = ph_mat[-g,]
edge_mat  = df[!duplicated(t(apply(df, 1, sort))),]
colnames(edge_mat) = c("Source", "Target")

singular_points = node_mat[!((node_mat$gene_name %in% edge_mat$Source)|(node_mat$gene_name %in% edge_mat$Target)),1]
singular_points = as.data.frame(cbind(singular_points,singular_points))
colnames(singular_points) = colnames(edge_mat)

edge_mat = rbind(edge_mat, singular_points)
edge_mat$Source = as.character(edge_mat$Source)
edge_mat$Target = as.character(edge_mat$Target)

# network object
net = network(edge_mat, directed = FALSE, loops = TRUE)

# pathway affiliation
x = data.frame(gene_name = network.vertex.names(net))
x = merge(x, node_mat, by = "gene_name", sort = FALSE)$pathway_number
net %v% "pathway" = as.character(x)


viz_net_obj = ggnetwork(net, arrow.gap = 0.02, layout = "kamadakawai")
viz_net_obj_mod = viz_net_obj
viz_net_obj_mod$x = viz_net_obj_mod$x+(cos(pi*(as.numeric(viz_net_obj_mod$pathway)%%num_pw-1)))+num_pw
viz_net_obj_mod$y = viz_net_obj_mod$y+(sin(pi*(as.numeric(viz_net_obj_mod$pathway)%%num_pw-1)))+num_pw
viz_net_obj_mod$xend = viz_net_obj_mod$xend+(cos(pi*(as.numeric(viz_net_obj_mod$pathway)%%num_pw-1)))+num_pw
viz_net_obj_mod$yend = viz_net_obj_mod$yend+(sin(pi*(as.numeric(viz_net_obj_mod$pathway)%%num_pw-1)))+num_pw

# looking up names by target coordinates
library(class)
viz_net_obj_mod$target.names = knn(train = viz_net_obj_mod[,c('x','y')], test = viz_net_obj_mod[,c('xend','yend')], cl = viz_net_obj_mod[,c('vertex.names')], k=1)

# Only connect high corrs
elim_list = list()
for(i in 1:dim(viz_net_obj_mod)[1]){
  if(abs(cor(og_df[,c(viz_net_obj_mod[i,c('vertex.names')])],og_df[,c(viz_net_obj_mod[i,c('target.names')])]))<0.5){
    elim_list = append(elim_list, i)
  }
}
viz_net_obj_mod_rest = viz_net_obj_mod[!row(viz_net_obj_mod_rest)[,1] %in% elim_list,]

centroid_df = viz_net_obj_mod_rest %>%
  group_by(pathway) %>%
  dplyr::summarise(
    count = n(),
    x = (max(x,na.rm=TRUE)-min(x,na.rm=TRUE))/2+min(x,na.rm=TRUE),
    xend = (max(x,na.rm=TRUE)-min(x,na.rm=TRUE))/2+min(x,na.rm=TRUE),
    y = (max(y,na.rm=TRUE)-min(y,na.rm=TRUE))/2+min(y,na.rm=TRUE),
    yend = (max(y,na.rm=TRUE)-min(y,na.rm=TRUE))/2+min(y,na.rm=TRUE)
  )
  

ggplot(viz_net_obj_mod_rest, 
       aes(x, y, xend = xend,yend = yend)) +
  geom_point() +
  geom_point(data = centroid_df,  shape = 21, col= "black", size=((num_pw*2.5)+0.7)^2, stroke = 2)+
  #annotate("point", x = 1, y = 1, shape = 21, size=50, colour = "blue", fill= NA)+
  geom_edges(aes(color = pathway), alpha = 0.25) +
  geom_nodes(aes(color = pathway), size = 1.5) +
  scale_color_brewer("Pathway", palette = "Set1")+
  xlim(0, num_pw*2.5)+
  ylim(0, num_pw*2.5)
```



```{r echo=FALSE,tidy.opts=list(width.cutoff=65), fig.height=3.5, fig.align='center', tidy=TRUE, comment=NA} 
y = as.numeric(dat$`Glucose 120 capillary blood who 85`[1:35])
X = as.data.frame(cbind(first_path_features,second_path_features))
group = as.factor(c(rep(1,2),rep(2,58)))
fit = grpreg(X, y, group, penalty="grLasso")
plot(fit)
compare = as.data.frame(cbind((abs(coef(fit, lambda=0.05)[2:60])>0.1),c(zero_status_xi_1*zero_status_gamma_1,zero_status_xi_2*zero_status_gamma_2)))

cvfit <- cv.grpreg(X, y, group, penalty="grLasso")
plot(cvfit)
```
